server:
  port: 8093

spring:
  application:
    name: poc-ses-email

aws:
  region: us-east-1
  endpoint: http://localhost:4566
  access-key: test
  secret-key: test
  ses:
    from-email: noreply@nameless.dev
