server:
  port: 8085

spring:
  application:
    name: poc-event-driven

aws:
  region: us-east-1
  endpoint: http://localhost:4566
  access-key: test
  secret-key: test
  eventbridge:
    bus-name: nameless-local-poc-custom-bus
